pactivate: Print better error message when distutils.cmd not present
The module `distutil.cmd` is required by the pip bootstrapper, and that
module is included in the standard Python distribution. Debian, however,
does not incude it in the `python3` package but in the `python3-distutils`
package, so it may not be present on a Debian-based system even when the
Python 3 interpreter is present.

The error message produced in such a case, a very long traceback followed
by "ModuleNotFoundError: No module named 'distutils.cmd'", is not very
informative about what the problem is. So we now first test to see if we
can import `distutils.cmd` and, if we cannot, fail with a suggestion that
the user may want to `apt-get install `python3-distutils`. That's exact
sugestion is only valid for Debian and its derivatives, but the user should
still get the general idea even if he's using another distribution that has
a similar issue.

diff --git a/cont-test b/cont-test
--- a/cont-test
+++ b/cont-test
@@ -50,6 +50,21 @@ echo '━━━━━ unknown argument error'
 [[ 'pactivate: unknown argument: xyz' == $(cat err-args) ]] \
     || { cat err-args; fail "bad message"; }
 
+echo '━━━━━ run pactivate without distutils'
+if (. $pactivate -q 2>err-distutils); then
+    fail "expected error without python3-distutils"
+else
+    msg="Cannot import 'distuils.cmd'; apt-get install python3-distutils?"
+    [[ $(cat err-distutils) == *$msg ]] \
+        || { cat err-distutils; fail "bad message"; }
+fi
+
+echo '━━━━━ installing distutils'
+apt-get -qq -y install python3-distutils >log-inst-distutils 2>&1 || {
+    cat log-inst-distutils
+    fail "apt-get install python3-distutils failed"
+}
+
 echo '━━━━━ run pactivate clean'
 #   This does the full bootstrap and virtualenv creation
 (. $pactivate)
