pactivate: separate bootstrap dirs for non-modern (<3.6) Python versions
We were already downloading different pip bootstraps for Python ≤3.5
because the current version of get_pip.py has dropped compatibility
with those earlier versions of Python. To avoid any chance of using
the wrong bootstrap code we now name the bootstrap directory for the
edition of get_pip.py we downloaded (Python major and minor version
number). This also may speed things by re-using a bootstrap when the
developer switches Python versions.

This change was considerably more difficult to implement than
expected, as the amount of changed code will indicate. The main
problem was that since we now need to get the Python version _before_
we determine the bootstrap directory name we need to quiet down (when
`-q` is given) all the verbosity of that process that previously
happened only once during bootstrap, rather than every time.

Other changes:
- We move the test of -q to an earlier test so we don't need to use it
  in the "run pactivate with options" test; this makes debugging the
  latter test easier.
- This includes some cleanup of cont-test to note the start and end of
  the test run and better name variables.

This really should be warning when the current virtualenv is not using
the same Python as the one the script would use for a fresh install of
that virtualenv; that's added to the to-do list.

diff --git a/cont-test b/cont-test
--- a/cont-test
+++ b/cont-test
@@ -13,9 +13,11 @@ trap 'fail "Unexpected exit"' 0
 ####################################################################
 #   Definitions and Functions
 
+echo "━━━━━ TESTS START with QUIET_TEST='$QUIET_TEST'"
 pactivate="./pactivate ${QUIET_TEST:+-q}"
-ve=/test/.build/virtualenv
-bsve=/test/.build/bootstrap/pactivate
+build=/test/.build
+virtualenv=$build/virtualenv
+bsve=$build/bootstrap/pactivate
 
 ####################################################################
 #   Tests
@@ -40,25 +42,39 @@ echo '━━━━━ run pactivate clean'
 (. $pactivate)
 [[ -x $bsve/pip ]] || fail "not executable: $bsve/pip"
 [[ -d $bsve/virtualenv/ ]] || fail "not a dir: $bsve/virtualenv/"
-$ve/bin/pip --version || fail "pip --version didn't work"
+$virtualenv/bin/pip --version || fail "pip --version didn't work"
 
 echo '━━━━━ run pactivate installed'
 #   This should do nothing but run the existing virtualenv's activate
-(. $pactivate && pip --version) || fail "pip --version didn't work"
+#   It also tests the -q option so we can leave it out (by default)
+#   for easier debugging in the more complex "with options" test below.
+(. $pactivate -q && pip --version) || fail "pip --version didn't work"
 
 echo '━━━━━ run pactivate with options'
-altbase=/test2/base; mkdir -p $altbase
+#   Alternate base dir configured for different Python interpreter.
+altbase=/test/altbase; mkdir -p $altbase
 ln -s /usr/bin/python2 $altbase/.python
 echo 'pyyaml>=5' > $altbase/requirements.txt
-(cd /tmp && . /test/pactivate -q -B $altbase -b /test2/build) \
+#   We re-use the existing build dir because we're testing download of a
+#   non-modern (2.7) Python bootstrap, so the bootstrap dir will be
+#   different; we need remove only the virtualenv.
+rm -rf $virtualenv
+#   Rebuild and check
+echo '───── running build'
+(cd /tmp && . /test/$pactivate -B $altbase -b $build) \
     || fail "build failure"
-echo '───── testing build'
-/test2/build/virtualenv/bin/python -c 'import yaml' \
-    || fail "yaml import failure; requirements.txt broken?"
-(. /test/pactivate -q -B $altbase -b /test2/build \
+[[ -d ${bsve}2.7 ]] || {
+    ls -la $build/bootstrap/;
+    fail "versioned bootstrap dir not found"; }
+echo '───── testing activation and Python version'
+(. /test/$pactivate -B $altbase -b $build \
     && v=$(python -c \
       'from platform import *; print("{}.{}".format(*python_version_tuple()))')\
-    && echo "version: $v" \
+    && echo "Testing version: $v" \
     && [[ $v == 2.7 ]]) || fail "wrong Python version: expected 2.7"
+echo '───── testing yaml import'
+$build/virtualenv/bin/python -c 'import yaml' \
+    || fail "yaml import failure; requirements.txt broken?"
 
+echo '━━━━━ TESTS COMPLETE'
 trap '' 0   # Turn off "Unexpected exit" failure
diff --git a/pactivate b/pactivate
--- a/pactivate
+++ b/pactivate
@@ -4,9 +4,11 @@
     || { echo 1>&2 "source (.) pactivate with Bash."; exit 9; }
 
 __pa_cleanup() {
-    unset __pa_cleanup __pa_builddir __pa_quiet __pa_python __pa_pyver \
+    unset __pa_cleanup __pa_echo \
+        __pa_builddir __pa_quiet __pa_python __pa_pyver \
         __pa_bootdir __pa_basedir __pa_requirements
 }
+__pa_echo() { [[ -n $__pa_quiet ]] || echo "$@"; }
 
 __pa_basedir=$(cd "$(dirname "$BASH_SOURCE")" && pwd -P)
 __pa_builddir=
@@ -18,28 +20,37 @@ while [[ $# -gt 0 ]]; do case "$1" in
     *)  echo 1>&2 "pactivate: unknown argument: $1"; __pa_cleanup; return 2;;
 esac; done;
 
-__pa_python=python3
-[[ -e $__pa_basedir/.python ]] && __pa_python=$__pa_basedir/.python
+__pa_echo '----- Checking Python interpreter'
+__pa_python=python3     # XXX should default to `py` for Windows
+#   Even if it's a dangling link (-e fails) we use it so that user sees error.
+[[ -e $__pa_basedir/.python || -L $__pa_basedir/.python ]] \
+    && __pa_python=$__pa_basedir/.python
+__pa_echo "Using $__pa_python"
+__pa_echo "Linked to $(readlink "$__pa_python")"
+#   Check $__pa_quiet before we evaluate $(...)
+[[ -z $__pa_quiet ]] && echo -n "Version: " && "$__pa_python" --version
+"$__pa_python" --version >/dev/null 2>&1 || {
+    echo 1>&2 "pactivate: bad python interpreter"
+    __pa_cleanup; return 3
+}
+#   $__pa_pyver is empty for "modern" versions of Python (i.e., those that
+#   can use the current get-pip.py, 3.6 and above) and otherwise is the
+#   major.minor revision number, suitable for use in the URL to download
+#   an alternate version of get-pip.py.
+__pa_pyver=$("$__pa_python" -c '
+from platform import *;
+if (python_version() < "3.6"):
+    print("{}.{}".format(*python_version_tuple()))
+')
+
 __pa_requirements="$__pa_basedir/requirements.txt"
 
 [[ -z $__pa_builddir ]] && __pa_builddir=$(cd "$__pa_basedir" && pwd -P)/.build
 
-__pa_bootdir="$__pa_builddir/bootstrap/pactivate"
+__pa_bootdir="$__pa_builddir/bootstrap/pactivate${__pa_pyver}"
 mkdir -p "$__pa_bootdir"    # also ensures that $__pa_builddir exists
 
 [[ -x $__pa_bootdir/bin/pip ]] || {
-    echo '----- Checking Python version'
-    echo "Using $__pa_python"
-    echo -n "Version: "
-    "$__pa_python" --version || {
-        echo 1>&2 "pactivate: bad python interpreter"
-        __pa_cleanup; return 3
-    }
-    __pa_pyver=$("$__pa_python" -c '
-from platform import *;
-if (python_version() < "3.6"):
-    print("{}.{}".format(*python_version_tuple()))
-        ')
     echo "----- Installing bootstrap pip (ver=${__pa_pyver:-latest})"
     curl ${__pa_quiet:+--silent} \
         "https://bootstrap.pypa.io/pip/$__pa_pyver/get-pip.py" \
