cont-test: Proper test for .python interpreter difference warning
We now check this in the main tests, rather than the special Debian-only
tests. What was holding us back from doing this before was the lack of a
second, different Python interpreter binary, but we fix this by just making
a copy of the standard binary and appending a newline to it. This runs just
fine, but is now technically a different file so that the compare with the
existing binary will fail.

diff --git a/tscript/docker-data/cont-test b/tscript/docker-data/cont-test
--- a/tscript/docker-data/cont-test
+++ b/tscript/docker-data/cont-test
@@ -88,6 +88,22 @@ echo '━━━━━ run pactivate installed'
 #   It also tests the -q option so we can leave it out (by default)
 #   for easier debugging in the more complex "with options" test below.
 (. $pactivate -q && pip --version) || fail "pip --version didn't work"
+echo '───── checking .python difference warning'
+#   This should print a warning message about the interpreter being different.
+#   This won't fail if the warning isn't printed, but you can at least manually
+#   confirm that it's there.
+#      Our "alternate" python binary is just the standard one with a newline
+#   appended to make it "different" from the standard one but still runnable.
+(cat $(type -p python3); echo) > /tmp/bin-python; chmod +x /tmp/bin-python
+ln -s /tmp/bin-python .python
+(. $pactivate -q 2>err-diffwarn && pip --version) \
+    || fail "pip --version didn't work"
+echo 'Warning message was:'; cat err-diffwarn
+[[ $(cat err-diffwarn) =~ 'WARNING: virtualenv/bin/python (' ]] \
+    || fail "line above is bad message"
+[[ $(cat err-diffwarn) =~ ') is not /test/.python (' ]] \
+    || fail "line above is bad message"
+rm -f .python
 
 echo '━━━━━ re-install virtualenv with .python symlink'
 clean_virtualenv
@@ -144,12 +160,6 @@ if $debian_tests; then
     echo '───── testing yaml import'
     $build/virtualenv/bin/python -c 'import yaml' \
         || fail "yaml import failure; requirements.txt broken?"
-
-    echo '───── checking .python difference warning'
-    #   This should print a warning message about the interpreter being
-    #   different. This won't fail if the warning isn't printed, but you
-    #   can at least manually confirm that it's there.
-    (. $pactivate -q && pip --version) || fail "pip --version didn't work"
 fi
 
 echo '━━━━━ TESTS COMPLETE'
