pactivate 0.5.10: Add `--` command line option
If no command-line options are given to pactivate it "inherits" $@
which, if nothing was explicitly passed, is probably non-pactivate
options. There's no reliable way for `pactivate` to tell if it was
called with explicit options or not (e.g., `"${a[@]}"` with an empty
array is a call without explicit options) and so no reliable way to
tell if $@ was intended or just accidentally set, from pactivate's
point of view.

So instead we allow callers always to specify a parameter that will do
nothing. Or in this case, almost nothing, since it's `--` and we do
follow the standard convention that `--` means "ignore all following
command line arguments." (It's just less confusing that way. And who
knows, it might even be useful to some callers.)

diff --git a/tscript/docker-data/cont-test b/tscript/docker-data/cont-test
--- a/tscript/docker-data/cont-test
+++ b/tscript/docker-data/cont-test
@@ -148,6 +148,13 @@ echo '───── removing .python symlink'
 rm .python
 (. $pactivate -q && pip --version) || fail "pip --version didn't work"
 
+#   This has to be after all the various tests above showing that the basic
+#   functionality works because it actually re-runs pactivate: we don't
+#   want a functionality failure to make it appear that argument ignore
+#   doesn't work.
+echo '━━━━━ ignores arguments after --'
+(. $pactivate -- -XX) || fail "didn't ignore args after --"
+
 echo '━━━━━ pactivate with -[Bb] and requirements.txt'
 echo '───── building altbase'
 altbase=/test/test-requirements; mkdir -p $altbase
